# Use root/example as user/password credentials
version: '3.1'

services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
     - ./db_scripts:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: "hellboy777"
      MYSQL_DATABASE: "challeng_r"
    ports:
      - 3306:3306
    networks:
      - challeng
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - challeng

networks:
  challeng:
    driver: bridge
